In [2]:
#Розв'язати 1 завдання з кожного підрозділу
#Завдання 1
import numpy as np
matA = np.matrix([[1,2],[4,-1]])
matB = np.matrix([[2,-3],[-4,1]])
matC = matA - matB
print(matC)

[[-1  5]
 [ 8 -2]]


In [18]:
#Піднести матриці до степеня
#завдання 1

import numpy as np
a = np.matrix([[-1,2],[0,1]]) 
b = np.matrix([[-1,2],[0,1]])
c = a.dot(b) #вирішив просто перемножити цю матрицю саму на себе, що є однаковим з возведенням в степень
print(c)

[[1 0]
 [0 1]]


In [19]:
#Знайти добуток матриць
#завдання 1
a = np.matrix('3 5; 6 -1')
b = np.matrix('2 -3; 1 2')
c = a.dot(b)
print(c)


[[ 11   1]
 [ 11 -20]]


In [13]:
#обчислити визначники
#завдання 2
import numpy as np
a = np.matrix('0 2 0; 3 4 5; 6 7 8')
a_det = np.linalg.det(a) #Визначник матриці
print(format(a_det, '.9g'))




    


12


In [11]:
#Обчислити визначники
#завдання 2
import numpy as np
a = np.matrix('2 3 4 1; 1 2 3 4; 3 4 1 2; 4 1 2 3')
a_det = np.linalg.det(a) #Визначник матриці
print(format(a_det, '.9g'))
c = -160 * -1
print(c)


-160
160


In [14]:
#Знайти обернену матрицю до матриць
#завдання 1
A = np.matrix('1 2 -3; 0 1 2; 0 0 1')
A_inv = np.linalg.inv(A)
print(A_inv)


[[ 1. -2.  7.]
 [ 0.  1. -2.]
 [ 0.  0.  1.]]


In [15]:
#Визначити ранг матриці
#завдання 1
A = np.matrix('1 2 3 4; 3 -1 2 5 ; 1 2 3 4; 1 3 4 5')
rank = np.linalg.matrix_rank(A)
print(rank)

2


In [17]:
#Розв’язати систему лінійних рівнянь методом Крамера, матричним методом
#завдання 13
a = np.matrix('1 -4 0; 2 -3 1; 1 4 2')
print('A=',a)
b = np.matrix('-5; -7; -1')
print('B=',b)

def kramer (a, b):
    a_det = np.linalg.det(A)
    print('Детермінант матриці = ', a_det)
#Зробити реревірку,що детермінант не дорівнює нулю
    if (a_det != 0):
        print ('Розв*язуємо систему')
        
        x_m = np.matrix(a)
        x_m[:, 0] = b # формування допоміжної матриці (1 ст. замінюємо на ст. b)
        print('x_m=', x_m)
        y_m = np.matrix(a)  #2 ст. замінюємо на ст. b
        y_m[:, 1] = b #2 c
        print('y_m=',y_m)

        z_m = np.matrix(a) #3 ст. замінюємо на ст. b
        z_m[:, 2] = b
        print('z_m=',z_m)

        x = np.linalg.det(x_m) / a_det
        y = np.linalg.det(y_m) / a_det
        z = np.linalg.det(z_m) / a_det
        print('X = ', round(x,5))

        print('Y=', round(y,5))

        print('Z=', round(z,5))
    else:
        print('Розв*язків немає')
kramer(a,b)


A= [[ 1 -4  0]
 [ 2 -3  1]
 [ 1  4  2]]
B= [[-5]
 [-7]
 [-1]]
Детермінант матриці =  0.0
Розв*язків немає


In [20]:
#1.Створіть прямокутну матрицю A, яка має N рядків і M стовпців з випадковими елементами. Знайдіть найменший стовпчастий елемент матриці A, для якого сума абсолютних значень елементів максимальна.

import numpy as np
n,m=4,5
a=np.random.random((n,m))-0.5
b=np.abs(a).sum(axis=0)
print(min(a[:, b.argmax()]))

-0.4619466496964588
